//
//  NameTableViewController.swift
//  Earl-Haig Clubs and Councils
//
//  Created by Harish Sharma on 2014-12-03.
//  Copyright (c) 2014 IshanCorp. All rights reserved.
//

import UIKit

class ClubListTableViewController: UITableViewController {

    let earlHaigClubs  = [
        EarlHaigClub("Anime and Gaming Club", "Alice Zhang", "ehssagc@gmail.com" , "Deborah Schwartz", "deborah.Schwartz@tdsb.on.ca", "", "Rm. 223 (may change to basement room)", "Mondays and Wednesdays from 3:30 to 4:30pm", "Anime and Gaming Club is divided into two sections that club members may choose to freely participate in. The gaming section provides a venue for playing multiplayer console games during club time. A handheld console gaming tournament may be held, depending on club member interest. The anime section is for the viewing and discussion of anime during club time. The goal of the anime section is to introduce uncommon and under-appreciated anime to members, in order to broaden their anime experience.   Our major annual event is the group ticket registration for Anime North, Toronto's largest anime convention. The club also provides assistance with transportation to the site of the convention.  ", "Speak with Club President(s) Alice Zhang and Jessie Kuan during club hours: Monday/Wednesday 3:30-4:40pm Rm. 223 (location subject to change in late Sept.)  Email name, phone number, and email to either: ehssagc@gmail.com z.alice213@gmail.com", "joystick-50"),
        EarlHaigClub("Archery Club", "Sebastian Gayowsky", "sebbieg19@gmail.com" , "Kate Hang", "kate.hang@tdsb.on.ca", "", "In the small gym", "Wednesdays after school", "The archery club will give students an opportunity to learn a fun sport that they have not been very involved with before. At the end of the year we may send some of our general members to a tournament. We hope to engage interest in an uncommon sport that has a very small population, and help it to grow. Through this club we will create a community based around a fun sport.", "Either come to the booth at the clubs fair or email earlhaigarchery2014@gmail.com", "center_direction-50"),
        EarlHaigClub("Arts Council", "Dexter Storey", "dexter.storey@gmail.com" , "Ms. Marshall", "stephanie.marshall@tdsb.on.ca", "", "English Hall", "Wednesday Mornings", "Arts Council is a club dedicated to promoting, creating and supporting art within the artistic community of Earl Haig. We host two main events: Battle of the Bands and Coffee House. We are also home to projects such as the Mural Project and the distribution of Arts Letters. ", "Applications for executive members are accepted annually in late May for the following year's arts council.", "brush-50-2"),
        EarlHaigClub("Athletic Council (EHAC)", "Olivia Moon", "kamponie@gmail.com" , "Mr. Mantziouras", "Telly.Mantziouras@tdsb.on.ca", "", "Room 253", "Every Friday morning at 8 AM", "The purpose of EHAC is to promote and support Haig athletics. The Earl Haig Athletic Council scores all home games, organizes school tournaments, intramurals,  hosts the annual student vs. teacher buy-outs, provides volunteering opportunities to students, and organizes the athletic banquet. The council assists the athletic department in running sports in and out of the school, in order to help athletics thrive at Earl Haig. ", "Although executive members have already been chosen for the upcoming school year, general member applications will be up on Sept. 22, 2014 on the SAC board. We encourage anyone interested in sports and athletics to be a part of this council! ", "sports_mode-50"),
        EarlHaigClub("Autism Awareness Canada Council", "Cindy Li", "cindyxrli@gmail.com" , "Andrew Fair", "", "", "Cafetaria, room 029", "Meeting times are e-mailed", "We will be raising money for children with Autism Spectrum Disorders (ASD) because we want them to live normally and socialize like the rest of us. We will be having many fundraising events inside of school, and volunteering at a Autism centre outside of school. We guarantee it will be a great experience. You will also be getting volunteer hours! ", "You can join in the beginning of the year by handing in an application form on the SAC board. You can join throughout the year by e-mailing the address provided here on the website for an application form. ","donate-50"),
        EarlHaigClub("Automotive Society", "Peter Gregorian ", "p.gregorian@yahoo.com" , "N/A", "N/A", "", "N/A", "Once started, it will be once a month", "The purpose of the club is to increase the automotive knowledge within our school community, as well as, provide a club for those who share a strong passion for the automotive culture and hope to learn more about the \"car life\". Activities within the club will include informal gatherings where we will discuss all the latest in automotive news, share our opinions and eventually work towards creating an Earl Haig Auto Blog! Not just for leisure, this club will also have some positive social aspects tied to it. In the spring and summer months, we plan to host a charity car wash as well as multiple car meets in order to give back to our community, or use the funds for a cool Earl Haig \"Carpe-mobile\" where students will get a chance to decorate the vehicle for a small fee (in this way we can raise some extra money for a charitable cause).  ", "New members will be able to join our club by filling out a simple online application where they will briefly state why they would be interested in joining the club and the ideas they can contribute for increasing Earl Haig's Automotive culture! ","automotive-50"),
        EarlHaigClub("Board Game Competion Club", "Luyi Lu", "Luyi@hotmail.ca" , "F. Boyd , M.Lee", "fiona.boyd@tdsb.on.ca ; Meng.Lee@tdsb.on.ca", "", "Room 296", "Tuesday Weekly", "Hey Haigers, do you want to flex your skills before others in your favourite tabletop past times? Are you eager to learn about all the tips and tricks to take your board game skills to the next level. Do you have a curiosity to learn new sources of board and card entertainment? If you answered yes to any of those questions, then this club will be the perfect match for you. We will be arranging a variety of classic and modern games, such as Chess, checkers, Eastern Go, Elephant chess, Monopoly, and many more. To make your experience more pleasing, we will accommodate people with all interests and skill levels.   If you are interested, please come to our meeting this Tuesday in room 246.  That is today afterschool in room 246. New members are always welcome. Hope to see you then! ", "Drop in during any of our meet time and you will usually be greeted with our delicious signature refreshment. However, eating aside, don't forget also the amazing game tutorials unfolding right in front your eyes!! You will end up so drawn to our presentations that you will be left wonder how all the food simply vanished >-<  ","dice-50"),
        EarlHaigClub("Boxing club", "Jacob Gao", "jacob041217@gmail.com" , "Mr. Sherman", "", "", "276", "Friday morning before school", "The purpose of Boxing Club is about strengthening the body and the skills for members. We will teach and discuss that boxing is not only about punching people, but also about teaching people how to manage their power and use them in a proper way. Our club will not just focus on fighting and working out, but concentrates more on mind training.", "  Members who would like to join should go through a process that analyze their body condition and their mind control ability. We should avoid that our members use the skills of boxing to violence and applies it negatively. The club will test them in body conditions using basic workout tools such as push ups, pull ups and sit ups. Also the club will create a mind quiz to test new members to ensure the least possibility for abusing other people.","boxing-50"),
        EarlHaigClub("Bridge Society ", "Frank Chen", "mcfrankshc@me.com" , "John Pascua", "j.pascua@tdsb.on.ca", "", "Room 127", "Friday after school every second and fourth week of the month", "The Bridge Society seeks to pass on the art of bridge-playing to the bright and eager young minds of tomorrow. It purpose is none other than to inspire a new generation of bridge aficianados to revitalize the 200-year old card game and the history that it proudly stands for.   Activities include beginner instruction sessions and regular game series.    ", "The Bridge Society welcomes members of all age and races. But one does not need to be a member to have fun at the bridge club. All we ask is that each player bring with them a spirit of camaraderie, generosity, and brotherly love to each game they play.  To join the Bridge Society, prospective members may contact Frank Chen at anytime of the day through email, phone or in person. He may be seen strolling to and fro the science hallway or fraternizing with the denizens of the wavy hall. If he cannot otherwise be located, you may speak to the lovely Mr. J. Pascua in the guidance office. Do so at your own discretion lest you incur his wrath. ","cards-50"),
        EarlHaigClub("BTTF (FASHION EVENT)", "Jackie Cheng & Sasha Huebener", "jackiechengxxiii@gmail.com" , "Ms. Sakhavarz & Mr. Hack", "nazysakhavarz@hotmail.com", "", "Art Rooms (301, 201, 303)", "Wednesday mornings & Thursday after school", "By using the theme Back to the Future, students will have to develop that concept into a fashion event.  Utilizing both Wave Hall and Wave Gallery, student curators have to plan and curate the space to not only support the theme, but other student designers' garments.  The Artistic Director and the Directors of Communication will assist the curators in the development and production of this event.  Will partner with VAC.", "Members have already been chosen.  ","shoe_woman-50"),
        EarlHaigClub("Campus Vibez", "Arvin Li", "campusvibez.ehss@gmail.com" , "Mr.Cariyanus", "", "", "room 160", "thursday", "Campus Vibes is a club that brings first hand information about different universities to high school students. We will be bringing in university students for them to share their own experiences throughout their university life.", "The club is open to everyone who is interested in finding out information about University.","university-50"),
        EarlHaigClub("Canadian Cancer Society", "Rachael Chung", "rachchung16@gmail.com" , "Ms. Antoniou", "tina.antoniou@tdsb.on.ca", "", "Room 307 (ms. Antoniou's room)", "Tuesdays afterschool (3:30-4pm), biweekly", "We will be fundraising throughout the year for the Canadian Cancer Society as well as raising awareness of cancer and the issues surrounding it, within the school. Events for the coming year include pink ribbon sales for breast cancer, and yellow daffodil sales in April, both accompanied by a dual way to raise money (selling merchandise/food). Other potential events include hosting Angel Hair donations and a larger fundraiser in the middle of the year (type of fundraiser to be determined, but it will be during school hours and nothing too large-scale). ", "Apply by filling out a GM application form, which will be provided in mid-September on the SAC board or contact Rachael Chung through email. We are not accepting executive members for 2014-2015 at this time. ","cancer-50"),
        EarlHaigClub("CANFAR", "Alexandra Churchill", "achurchill97@gmail.com" , "Mr. Dixie", "", "", "Room 229", "Tuesday Mornings", "The Canadian Foundation of AIDS Research aims to raise awareness and money for AIDS research.  The club focus on two major events during the year, World's Aids Day (Dec. 1) and Kisses 4 CANFAR, where we help promote knowledge and prevention of AIDS.", "Apply for an executive position by filling out a form on the sac board or apply to be a General Member by signing up on the sac board or coming to the first meeting the second week of November.",""),
        EarlHaigClub("Cantonese Culture Club", "Ausco Cheng", "ra@menddez.com " , "Mr. Lau", "edmondlau722@gmail.com", "", "129", "tuesday", "This club is to synergize people who speaks cantonese together to make new friends in this minority group in ehss. As a culture club, different cultural events may be set up over time. A multicultural lunch table is what we set up last year and it was very successful. We also try to spread the canton culture to let more people understand what it is. For people who are already familar with cantonese, we will also try our best to strengthen their linguistic skills by adding different up to date slang to their vocab understanding and knowledge. Also we will also be consistent in connecting our culture with different other culture. To increase the international position and fame of the cantonese language and encourage more people to learn it. Apple, Kiwi, EZ.", "You can register for the club by asking the president directly at any time in earl haig.","great_wall-50"),
        EarlHaigClub("Caring for Cambodia", "Emily Deng", "emilydeng10@hotmail.com" , "Ms. Fradkin", "Leslie.Fradkin@tdsb.on.ca", "", "Room 344 science classroom", "Twice a month ", "Our goal is to provide a better and brighter future for the children of Cambodia through the education of science. We want to empower the teachers and show them exciting and cool experiments that would provide a life changing experience for their students. We want to inspire them to connect ideas and think beyond the classroom. We want to give students in developing countries access to the same kind of experiments that we take for granted here. But most importantly, our club will show that we Canadians care about them. That we want to make a difference in their lives and that we fully support them in their education. During the school year, we will be filming videos on how to conduct a variety of experiments. We will also be creating fundraisers to raise money for lab equipments.", "New members may join at the end of Novemeber and during December. Applications will be posted on the SAC board and announcements will be made. Students can contact Ms. Fradkin in the science office for more information.  ","pagoda-50"),
        EarlHaigClub("Carpanatomy", "Sarah Ge, Kitty Cao", "carpanatomy@gmail.com" , "Ms Yermus", "students1314@lepervalley.com", "", "Every four to five weeks", "Every four to five weeks", "-general members write articles -editors edit and write articles -newspapers are printed 3 times a year", "-deadline for joining has already passed but... -join by answering questions on an application created by the senior editor and writing an article -applications can be found on the board in the English hallway -contact carpanatomy@gmail.com for more information ",""),
        EarlHaigClub("Chinese Homework Club", "Melissa Pan and Alicia Gu", "aliciaguhi@gmail.com" , "Jane Wu", "", "", "Room 128 ", "Tuesdays afterschool until 4:30", "Ni Hao! For those with a Chinese background who are new to Canada and/or to the English language, Chinese homework club is THE club to join! We offer help to those who are having difficulties with understanding their homework in a foreign language, and provide tutoring for various subjects. We will also introduce some interesting events happening in the school. For those interested in becoming a tutor, volunteer hours will be give. Last but not least, snacks are provided!", "Anyone interested can drop in on Tuesdays afterschool in room 128. Feel free to contact Ms. Jane Wu (school settlement worker in the Guidance office, available Mondays, Tuesdays, and Fridays), Alicia Gu and Melissa Pan for details.","great_wall-50"),
        EarlHaigClub("Chinese Students Association (EHCSA)", "Bowen Ma", "csa.earlhaig@gmail.com" , "M. Lee", "yit.lee@tdsb.on.ca", "", "294", "Thursday after school from 3:45-4:30", "Earl Haig Chinese Students Association (the former Chinese Culture Club) is committed to prove a platform for all the students with Chinese background as well as those who are interested in the Chinese culture. It is a place for everyone to get connected with each other and for their voice to be better heard by the school.  We are adhering to serve Chinese students with the goal to help them better integrate into Canadian school life, to create an enjoyable learning, social and recreational atmosphere for all.  The E.H.C.S.A. WeChat subscription account is updated daily with translated school announcements, important school information, events information and volunteer opportunities. We will happily answer any questions 24/7 and new members are always welcomed.   ", "New members are always welcomed to join.  Simply complete the online registration form at anytime that would take less than 5 minutes:  https://docs.google.com/forms/d/1rHCM_aWnl3gyCS5GKTdh8CRPpql_w3bM4l2ZUTAJ7BU/viewform","great_wall-50"),
        EarlHaigClub("Claude Watson Ambassadors", "[NO ACTUAL PRESIDENET -- ONLY EXECUTIVE REPRESENTATIVES OF EACH MAJOR)","","","","","","","","",""),
        EarlHaigClub("Cooking Club", "Aira Harutyunyan", "thecookingclub@chef.net" , "Mr.Carayanis", "spiros.carayanis@tdsb.on.ca", "", "Room 160", "once a month on Wednesdays, at 3:40 pm.", "The intention of the Cooking Club is to have members enjoy the versatility and creativity of cooking and the ability to learn many recipes to enrich their everyday diet! Mainly however, it exists for us all to have fun and eat delicious food made with our own hands! During the school year, in addition to regular cooking sessions once a month, we plan to host many events including collaborations with other clubs, cooking competitions, and bake/meal sales to fund our club.", "New members can join our club by providing their contact information up on the sign up sheet that the club will place in the main hallway. They will be emailed the information regarding the details of the club.","cooking_pot-50"),
        EarlHaigClub("COPE", "Douglas Lawrence", "douglas.lawrence@tdsb.on.ca" , "Mr.Lawrence", "douglas.lawrence@tdsb.on.ca", "", "Guidance Office", "Thursdays; Period 3 lunch", "Previously known as Stop the Stigma,  Cope is an initiative in which addresses and teaches students about the topic of mental illness, the stigma surrounding mental health issues , and on sustaining and improving overall mental health and happiness! ", "Talk to Mr.Lawrence in the guidance office","hospital-3-50"),
        EarlHaigClub("Covenant House", "Bright Lee", "bright2009@live.ca" , "Mr. Risto", "", "", "Room 311", "Thursday Afterschool", "To raise awareness of homeless youth in Toronto aged 16 to 24, and to fundraise for donations towards Covenant House Toronto.", "We will be posting GM applications on the SAC board. ","donate-50"),
        EarlHaigClub("Cricket Club", "Aniruddha Das", "dasaniruddha1999@gmail.com" , "Mr.Kettle", "Robert.Kettle@tdsb.on.ca", "", "Small gym", "Every Friday after school", "If you are interested in playing some good competitive cricket then the E.H cricket club is the place for you, our cricket club participates in two of Toronto's major school leagues; the TDSB league and the Mayor's cup. ", "Just attend the practice after school every friday at the small gym or contact Mr.kettle or email at dasaniruddha1999@gmail.com. You can also find us on Facebook, earl haig boys cricket team. We usually meet in the small gym but if the big gym is available we switch to that.","cricket-50"),
        EarlHaigClub("Cuber's Association", "Kevin Kordbacheh", "kevin_kordbacheh@hotmail.com" , "Mme. Rosvelti", "", "", "Room 246", "Wednesday's 3:30-4:30", "The Cuber's Association is a club dedicated to teaching students how to solve the Rubik's cube as fast as as they can by the end of the school year. We have no plans for in school event's or activities during the 2014/2015 year.", "Simply show up in room 246 Wednesday's after school with an interest in learning how to solve a cube. Everyone is welcome. ","front_view-50"),
        EarlHaigClub("Dance Council", "Alice Guo", "allieguo@gmail.com" , "Tara Lee-Blight", "", "", "Room 139", "Monday morning", "Dance Council not only represents the Earl Haig's Dance Department, but also strives to weave dance into everyday life at school. Between planning flash mobs and holding Buddy Breakfasts, this council also assists in the production of Dance Collective Night and designing dancewear for both the majors and electives. Dance Council hopes to bring out the inner dancer in each and every Haiger because just as Martha Graham once said, “Nobody cares if you can't dance well. Just get up and dance. Great dancers are great because of their passion.” ", "The General Member sign up list is on the Dance Council board in Room 139. There will be two meetings a month on Monday mornings. Feel free to contact Alice Guo with any questions/concerns at 647-470-0168.","dancing-50"),
        EarlHaigClub("DECA ", "Newton Xu", "newton.xu@hotmail.com" , "Michael Canzi", "m_canzi@hotmail.com", "", "Room 285 ", "Wednesday afterschool", "By creating partnerships between business and education, DECA Ontario provides real-world experiences in the fields of marketing, business, law, and entrepreneurship to develop high school students into character-driven leaders enriching our businesses and communities.  Earl Haig DECA, the Haig DECA chapter, represents Earl Haig at the Regional, Provincial and International levels of competition hosted by DECA Ontario. Participants have the opportunity to represent Ontario at the International Career Development Conference (ICDC) in Orlando.  ", "Interested members can come to the information meetings on Sept.10-11 in O'Grady Hall at 3:45 pm.  Registration will be available online starting September 12th. Check the \"Earl Haig DECA\" Facebook page or the DECA board outside room 285 for details.  Payment for the competition will be collected September 17th in room 285.   For questions, please e-mail Newton Xu.  ","bullish-50"),
        EarlHaigClub("Delphian Yearbook", "Amanda Lee, Shirley Jiang, Sumin Oh, Zong Li", "ehdelphian@gmail.com" , "Walter Raemisch", "walter.raemisch@tdsb.on.ca", "", "Yearbook Office", "Varies", "The Earl Haig Delphian Yearbook team is group of dedicated members who, year after year, produce the award-winning yearbook that features over 2 200 students in only 200 pages.", "The Editor-in-Chief 15/16 auditions begin in May 2015. The Assistant Editor-in-Chief 15/16 auditions begin in May 2015. Sectional Editor 15/16 applications are in June 2015 and September 2015. General Member 14/15 applications are due by Friday, October 17th, 2014. Contact ehdelphian@gmail.com for more details.","school-50"),
        EarlHaigClub("Design Team", "Sumin Oh", "ehss.so@gmail.com" , "Mr. Raemisch", "walter.raemisch@gmail.com", "", "202", "Depends", "Please do not share this: We were approached by school administration to rebrand the school. Currently, we are working on logo design and brochures. ", "Members are now unavailable to join. If truly interested they may contact Sumin Oh at ehss.so@gmail.com. Students must have experience in Illustrator and a mini-portfolio to demonstrate graphic work. ","design-50"),
        EarlHaigClub("Diem Magazine", "Noah Kahansky and Deanna Petcoff", "Noah: noahkahansky@hotmail.com  Deanna: deanna.petcoff@gmail.com" , "Nazy Sakhavarz", "", "", "Third Floor Art Studio", "TBD", "Diem Magazine is the arts and culture publication of Earl Haig. There are no staff contributors, and freelance submissions from all students are considered. Diem Magazine recognizes the importance of free press and seeks to provide a voice for all who wish to participate. Both online and print editions are created by the students and for the students, and are a great way to keep up with Earl Haig's artistic community.", "You can join Diem Magazine by picking up an application form on the Diem board on the third floor, and submitting it by Friday, September 19. ","school-50"),
        EarlHaigClub("Drama Council", "Kasi McAuley", "Kasi@muskokawoods.com" , "Laura Nienhuis", "Laura.nienhius@tdsb.on.ca", "", "Room 102", "Thursday Mornings", "The Drama Councils purpose is to unite all areas of drama at Earl Haig! We run workshops, host drama parties, decorate the drama board and many other fun things. ", "Contact Kasi McAuley at Kasi@muskokawoods.com if you want to get involved. ","theatre_mask-50"),
        EarlHaigClub("ECO Club", "Mariel Terebiznik", "eco.haig@gmail.com" , "Ms. Savicki", "meraya.savicki@tdsb.on.ca", "", "room 130, room 342, library", "The whole club meets on the first Wednesday of every month. Each separate council meet weekly on different days", "ECO is the environmental council. We work at making this school a more eco-friendly place by promoting an eco-friendly lifestyle, organizing events and initiatives, as well as helping clubs, councils and the administration make environmentally conscious choices. We are one of the biggest, most active clubs at this school, with over 30 executive members and initiatives throughout the whole school year.  ", "We will have more online general member applications available in January. If you would like the link, either email us at eco.haig@gmail.com or like our Facebook page at Earl Haig ECO Happenings","recycle_sign-50"),
        EarlHaigClub("ESL Council", "Clara (Mu) He", "clara.clara.he@gmail.com " , "Ms. J. Jundler; Ms. J. Zhou", "janet.jundler@tdsb.on.ca; dearmszhou@gmail.com", "", "Rooms in the ESL hallway (specific location announced prior to the meeting)", "GM meeting time varies among committees ", "Earl Haig Secondary School's ESL council strives to provide the students new to Canada a better learning environment helping them to faster adjust to their new lives. Also we are in charge of big events like annual multicultural lunch inside of the school. And the money we collect from those events and fundraisers will be donated in April.", "GM selection is based on GM application forms (due early October)","add_user-50"),
        EarlHaigClub("Film Arts Council", "Stephanie Davis & Marteen Sevier", "stephdavis8e@gmail.com" , "Katherine Yamashita ", "", "", "Room 202", "Mondays after school ", "Film Arts council serves as a meeting place for Film Arts students to have a voice in their Claude Watson major student body, express concerns and ideas about the program and meet fellow Film Arts majors. This council plans fundraising, social events as well as the annual Film Arts Night showcase.", "Contact Stephanie Davis, Marteen Sevier or Lauren Gerber on Facebook, or come to Film Arts council meetings on Mondays after school in room 202.","movie-50"),
        EarlHaigClub("Footprints Christian Fellowship ", "Jessica Moon", "jessica7moon@hotmail.com" , "Mr. Im ", "phillip.im@tdsb.on.ca", "", "Room 248 ", "Tuesdays After School ", "Our purpose is to unite Christians at Earl Haig Secondary School while serving and worshiping our God as one body and one vessel.   ", "Anyone can join at any time of the year!  Just come right to room 248 after school on Tuesdays if you are interested!  If there are any questions concerning Footprints Christian Fellowship, feel free to contact the club at footprintschristianfellowship@gmail.com. ","cross-50"),
        EarlHaigClub("Foreign Relations/Diplomacy Club", "Alicia Gu", "aliciaguhi@gmail.com, ehdiplomats@gmail.com" , "Jane Wu", "", "", "room 128", "fridays", "The Diplomacy Council is an organization where students are able to connect with representatives from different countries in Canada. We aim to educate and raise interest in the field of foreign relations. During the school year, members will have opportunities to meet consul generals of multiple countries, attend national anniversary celebrations of various cultures, watch memorable flag-raising ceremonies in person, and learn as well as experience the diverse cultures in Canada, such as learning a new language for free (courtesy of consulates in Toronto)", "Because cultures have no limits, we do not want to give students the feeling of restriction. Therefore, anyone is welcome to join. They can do so by filling out a simple form online: https://docs.google.com/forms/d/1zRoTKGkwYvVIeLjVy4HCSSwfcilHIl807-pEwTGSwLc/viewform?usp=send_form  Because meetings do not happen every week, those interested could contact our email for further information: ehdiplomats@gmail.com","globe-50"),
        EarlHaigClub("Free Geek", "Jackie Ke", "jackieke724@hotmail.com" , "Dr. Noukhovitch", "sacha.noukhovitch@tdsb.on.ca", "", "271A Computer lab", "Friday 3:30", "The purpose of this club is to create connections between our school and \"the United Way non-profit, social enterprise organization\", Free Geek Toronto. Club members can have more access than ever to use and learn computer technology through this club. For those who are interested in learning new computer languages, we have a programming class set up in our club, and teachers who have years of teaching and experience of programming will instruct students weekly about a unique language, J.  There is also a build class that allows students to learn about hardware. It is even possible for each student to make their own computers out of different recycled components. Some of them will be sold as donation to charity. During the year, we will frequently organize events such as recycling used computer parts which can be re-used in the build program. At the end of the year, we will try to find industrial sponsors who may be interested at students' skills and can even get them a part-time job during summer!  ", "The club will start recruiting members on Sept.22 for a week or two. There will be a sign-up form on the SAC board for students to write down emails and names. They can also join the club by attending the after-school meetings on Friday.  Please contact Jackie, jackieke724@hotmail.com, or Hangzo, hangzuoxiang@gmail.com, if you have any questions. Everyone's welcome!","nerd-50"),
        EarlHaigClub("Free The Slaves", "Reena Chen", "isrc33@gmail.com" , "Ms.Antoniou ", "", "", "Room 307", "the first and third Thursday of every month.", "the purpose of this club is to raise awareness that there are still slaveries going on in the world, and we are working along with the free the slaves organization to raise awareness, collect funds, and help out the slaves by doing what we can to help.", "We will have a signup sheet at the club fair, where people can leave their email address, or just come to our first meeting, we will accept GMs there. The first meeting is going to be on Thursday Sept 25th 2014, After school in room 307.","oppression-50"),
        EarlHaigClub("Front Of House", "Adham El Sharkawy", "hand97@gmail.com" , "Mr. Derek Sherman", "dereksherman01@yahoo.ca", "", "Business Classes (usually 276)", "Mid Sept. ", "The purpose of the club is basically to help out councils such as the music council for instance in their events such as the school show, school dance, graduation and much more. We usually sell tickets to such events or attend these events to supervise and help out during the event. We also try encouraging new students to join to make them active in school activities and interesting events and help them get used to the school and get to know new people around.", "We usually put form up on our board and then people fill up the forms and we take the most suitable and responsible members and then shortly after we make a meeting to welcome these members and get them to know what they should do and everything. This usually happens during september. You could always contact me or Mr. sherman for details and clarification. ","donate-50"),
        EarlHaigClub("Future ACES Council (FACES)", "Tina Lei", "tinalei_74@hotmail.com" , "Ms. Stewart", "Tanya.Stewart@tdsb.on.ca", "", "Room 117", "Tuesday After School", "FACES is one of the larger councils at Earl Haig and represents the Future Aces Creed. Our mandate is to help youths develop the self-knowledge and self-confidence that will enable them to take control of their lives and use their abilities in a positive way. We provide opportunities to participate in enriching events like PEACE Week, Pink day, Purple day and hosting workhops at Cummer Valley Middle School. ", "We are now recruiting General members! Pick up an application on the   SAC board in the main hall or on the FACES board in the languages hallway on the second floor. Applications are due this Friday, October 3rd.",""),
        EarlHaigClub("Future Successors", "Armin Barati", "armin.barati@hotmail.com" , "Mr. Cheslo", "", "", "311", "Tuesday Afterschool", "The aim of our club is to help students gain a basic understanding of how businesses work in the real world, as well as teaching them the essential principles necessary for a business to strive. Most students have an inner drive for business, however, due to their course load, they weren't able to take a business course. We are there to help fulfill their business-driven passions. Throughout our meetings, we will be giving them information regarding the inner workings on how to run a business, and how to be successful doing so, as well as delivering valuable organizational tips.", "New members are welcomed to join us at any of our meetings, which will be held weekly,wednesdays, throughout the month of October (Room number to be determined). Executive applications are available by contacting myself or the vice-president (Parham Rownaghi) directly. They will also be posted to various social media. (Yay, eco-friendly) Alternatively, we will be holding a student registration available to all students throughout Clubs Fair.",""),
        EarlHaigClub("GSA (Gay Straight Alliance)", "Alisa Kanda Kovac", "alisa.kandakovac@outlook.com" , "Mr. Go", "speeritual@gmail.com", "", "Library", "Thursday Afterschool", "GSA (Gay Straight Alliance) is for people, whether you're lesbian, gay, bisexual, transgender, anything in between or simply support and advocate equality. Our mission is to raise awareness about the LGBTQ community, advocate anti-homophobia and anti-bullying, and ultimately, create a safe environment for everyone.  We will be having fundraisers, awareness days and equality promotion meetings. We will also do Pink Day (anti-bullying and anti-homophobic) as a school wide event. ", "Soon, we will be having an application process for executive members and are hoping to have gm meetings throughout the year.  All information about the club and information meetings will be posted on the GSA board on the second floor. The same information will also be posted on the clubs' website: http://earlhaiggsa.wordpress.com Anyone with inquires can feel free to contact me at alisa.kandakovac@outlook.com",""),
        EarlHaigClub("Haig Network", "Robert Pan", "earlhaig.network@gmail.com, robertpan226@gmail.com" , "Ms. Wun", "lianne.wun@tdsb.on.ca", "", "Room 040", "Tuesday Mornings Biweekly", "A club/team of students to run, maintain, and upgrade Haig Network, a social platforms for clubs and councils.", "Members are to fill out a google docs application to list their computer and programming skills and Haig Network will select them based on their skill level, communication skills and club requirements. Members can contact the executives, Robert, Stephanie, Kitty, and Ryan or the staff sponsor, Ms. Wun. Applications for Haig Network will be out near the end of September on google docs.","active_directory-50"),
        EarlHaigClub("Haig Stock Exchange (HSE)", "Kristen Li", "kristenmuhengli@gmail.com" , "Mr. Safarian", "", "", "275", "Thursday after school", "Haig Stock Exchange is a club that exposes students to the financial market. Financial literacy will be taught and discussed in the club meetings. We will also have stock market simulation games that encourages students to participate and give them a feel of how the real market works. ", "Members can join by coming to the club meetings. Contact information will be collected in the first few meetings. ","money_exchange-50"),
        EarlHaigClub("Healthy Living", "Nancy Zhang", "nancyzhang088@gmail.com" , "Ms.Leo", "", "", "Room 029", "2-3 Times/Month", "The goal of this club is to bring awareness among high school students about the benefits of a healthy lifestyle. We will be focusing on different monthly subtopics. We will also have monthly events such as Healthy Eating Day (Free samples of fruits and vegetables) in order to raise awareness and help promote a healthy life style.   ", "General Members can join by emailing Nancy at nancyzhang088@gmail.com and providing their contact information: First and last name, grade, email address and phone number. If you are interested being an executive member please email Nancy for more information. I hope you'll join this friendly and awesome club! :)  ","vegetarian_food-50"),
        EarlHaigClub("Heart & Stroke Committee", "Aryana Rabii", "aryrabii@hotmail.com" , "Ms. Kate Hang", "Kate.Hang@tdsb.on.ca", "", "Rm. 342", "Thursday Mornings", "The purpose of this club is to raise awareness towards heart disease and stroke. The club will be holding events to fundraise for the Heart and Stroke Foundation of Canada. Some examples of events that the club may hold are a jump-rope contest, healthy food sales during lunch, and participation of the annual Becel Heart & Stroke Ride for Heart Toronto. ", "Within about a week, the Heart & Stroke Committee will post general member forms on the clubs & funds board. The applications will include brief questions that will reflect the applicants' interest in joining the committee. My e-mail address, aryrabii@hotmail.com will be included in the application, in order for the general members to be able to easily contact me if they have any questions. The forms will have about a 2-week deadline. ","heart_monitor-50"),
        EarlHaigClub("HOSA", "Kevin Kordbacheh", "kevin_kordbacheh@hotmail.com" , "Avila De Sousa", "avila.desousa@tdsb.on.ca", "", "Room 346 or Room 348", "Thursday", "HOSA “Future Health Professionals” is a national student-led organization run by and for students interested in pursuing careers in the health professions.  HOSA is an exclusively health-careers oriented organization; we can devote one-hundred percent of our resources to helping students become effective, compassionate,health professionals and leaders in their chosen field of work. The unique benefits of HOSA include volunteer service opportunities, over $300,000 in scholarships across the nation, educational symposiums led by leaders in the healthcare professions, forty-one different competitive and recognition events at the national and international conferences, networking opportunities with HOSA’s forty-nine official business and healthcare industry partners, as well as leadership opportunities at the local, provincial, and national levels.All health science schools highly prefer applicants who demonstrate both an interest in, and actual hands-on experience with, healthcare-related community service, leadership, and academic achievement. HOSA membership provides students with all of these key opportunities.  ", "Firstly, we will make announcements regarding the recruitment days. New members can join our club by attending our inaugural meeting in room 346 on October 16th and signing up on our HOSA Prospective Member Sign-Up Sheet after an introduction to what HOSA is. The second meeting will also be available for more sign-ups","steathoscope-50"),
        //EarlHaigClub("⧜ IMC (Infinity Math Club)", "Shuo (Kevin) Diao", "diaokevin01@gmail.com" , "Ms. Scholler; Ms. Wun", "Lianne.Wun@tdsb.on.ca", "", "Rm. 296", "Every week on Thursday", "Infinity Math Club seeks to help students improve their critical-thinking and problem-solving skills, help students with math problems, and prepare students for math competitions (e.g. Euclid, AMC, COMC, Pascal/Kayley/Fermat, Fryer/Galois/Hypatia). IMC will hold weekly meetings to provide its students with help in math and coach them for contests.", "Come to our weekly meeting in room 296 to a part of Earl Haig's IMC. If you have any concerns, questions, or suggestions for IMC, please contact Shuo (Kevin) Diao at diaokevin01@gmail.com or via (647)202-1888.",""),
        EarlHaigClub("IMC (Infinity Math Club)", "Shuo (Kevin) Diao", "diaokevin01@gmail.com" , "Ms. Scholler; Ms. Wun", "christine.scholler@tdsb.on.ca; lianne.wun@tdsb.on.ca", "", "Rm. 296", "Every week on Thursday", "Infinity Math Club seeks to help students improve their critical-thinking and problem-solving skills, help students with math problems, and prepare students for math competitions (e.g. Euclid, AMC, COMC, Pascal/Kayley/Fermat, Fryer/Galois/Hypatia). IMC will hold weekly meetings to provide its students with help in math and coach them for contests.", "Come to our weekly meeting in room 296 to be a part of Earl Haig's IMC. If you have any concerns, questions, or suggestions for IMC, please contact Shuo (Kevin) Diao at diaokevin01@gmail.com or via (647)202-1888.","infinity-50"),
        EarlHaigClub("IND Club", "John Zhong", "theindclub@gmail.com, wjz.john@gmail.com" , "Ms Kardish", "sasha.kardish@tdsb.on.ca", "", "room 211", "Every Monday Afterschool", "The Initiative for Neuroscience and Dementia (I.N.D.) is an organization whose sole purpose is to effectively promote and fund research to find cures for devastating and widespread neurological diseases. I.N.D. will provide a continuum of support services to other organizations pursuing further research for cures towards neurological diseases and other areas in the field of neuroscience and mental health. Established in 2011, I.N.D. was built and operates under the principles of youth leadership and volunteerism ", "Pick up a GM application form on the SAC board or join anytime during the year.","counselor-50"),
        EarlHaigClub("JSU (Jewish Student Union)", "Aby Volcovich", "aby@volcovich.com , earlhaigjsu@hotmail.com" , "Mrs. Krakowski", "", "", "276", "Tuesdays after school", "SHALOM!  The Jewish Student Union is a club where anyone can come and learn and talk about Jewish life and culture. We talk about holidays and Jewish values, as well as do various community volunteer activities. There is always kosher pizza at the club as well as fun activities. The purpose of the JSU is to create a Jewish community at Earl Haig where all questions are encouraged and answered.   This year we plan on creating a Holocaust remembrance assembly to educate and commemorate the lives lost. Assemblies such as these are crusial so that \"NEVER AGAIN\" really fulfills its statement.  ", "Come to the weekly meetings, or also contact any of the members for info on when meetings are... Basically in order to be part of the club just somehow come to the meetings or ask about events being organized so you can help or participate in them.","star_of_david-50"),
        EarlHaigClub("Junior Council", "Amirah Mobarak", "amirah_mobarak@hotmail.com" , "Francis Lue", "", "", "cafeteria, room 212, or room 117", "Every week/every other week", "Junior Council is a council made up of grade 9 and 10 students. We are responsible for many different junior events throughout the year. This includes the RAD (radical advice development) program, Junior Movie Night, Junior Assembly, Junior Day, and any other events we come up with as a council.", "Junior Council has already been formed since mid-September. It was through an application process. ",""),
        EarlHaigClub("KEY Club", "Nicole Zhao", "nzhao98@gmail.com" , "Ms. Fradkin, Mr. Mullaley", "leslie.fradkin@tdsb.on.ca, john.mullaley@tdsb.on.ca", "", "Room 117", "Once a month on Tuesday ", "The purpose of the club is to use to power of youth to impact and inspire youth all around the world. We will be holding 1-2 fundraisers every 2 months as well as participating in out of school activities such as District Convention and KEY Leader. All proceeds will go to Muscular Dystrophy Canada and the ELIMINATE Project. ", "Applications for GM and exec positions are in the beginning of the year (September, October) and may also be in January. For questions please contact Nicole Zhao at nzhao98@gmail.com.",""),
        EarlHaigClub("Knitting Club", "Thea Robinson", "theamcrobinson@gmail.com" , "Ms. Rosvelti", "susanna.rosvelti@tdsb.on.ca", "", "room 246", "Wednesdays from 3:30-4:30pm", "We are a close knit (get it?) group of people who hang out and knit once a week, and sometimes we have snacks.", "Everyone is welcome! Simply email the president with any questions, or just show up if that's your style.","scarf-50"),
        EarlHaigClub("Korean Homework Club", "Junhee Park", "ilpjh98@gmail.com" , "J. Pascua", "", "", "room 128", "every Thursday", "as tutor, help korean who need help on there homework or test study or as tutee, come to meeting and get help from tutee.", "just come to the meeting place(room 128) every Thursday","yin_yang-50"),
        EarlHaigClub("Leadership Council", "Alyssa Li", "alyssayingli@gmail.com, director.ehlc@gmail.com" , "Ms. Lue, Ms. Scholler, Mr. Griesz", "haig.lue@gmail.com, christine.scholler@tdsb.on.ca, michael.griesz@tdsb.on.ca", "", "Room 249, O'Grady Hall", "Thursday mornings at 8:00 AM", "The Leadership Council promotes leadership within the student body and organizes numerous events during the school year, including Grade 9 Orientation Day, Parent Social & BBQ, TTC/School Photo Day, Winter Hamper, Parent-Teacher Interviews, Volunteer Fair, and Grade 12 Commencement. We make sure that every student has a chance to be engaged in the different opportunities offered at Earl Haig. ", "New members can join Leadership Council by filling out a GM application which is located on the LC board. They can contact director.ehlc@gmail.com at anytime regarding applications, or they can talk to the LC executive members in the LC office (room 249) if they have any questions. ","administrator-50"),
        EarlHaigClub("League of Legends Club", "Emily Zheng", "emily.zheng0@gmail.com" , "Robbie Risto", "robbie.risto@tdsb.on.ca", "", "Room 310", "Thursday After school", "League of Legends Club was created to bring League players of Earl Haig Secondary School together. We serve the sole purpose of allowing students to have fun while keeping up with their academic work because high school can be very stressful and a lot of young people turn towards games as a way of relaxation.  The club will hold several tournaments in which teams of 5 can compete against each other for not only the title of the best team in school but also a prize at the end of each tournament. The first tournament taking place at the end of November will be an in-school tourney meaning only students of EH can join. The tournaments after that will be between several other high schools in Toronto as the game is very popular among this generation. ", "The club sign-up sheets are posted up on the SAC board in the beginning of the school year and we also hold an information meeting where sign-ups are also available.  The club has a Facebook group of over 200 members and people who are interested in joining would usually join the Facebook group. We will then ask for their email in order to contact them and their Summoner Name (name within the game) so they can be included in our events and added to our attendance.  If a student is interested in joining but does not have a Facebook account, they can find me or the Vice President, Haozhou, to sign up for the club. ","joystick-50"),
        EarlHaigClub("Library Volunteers", "Anupya Pamidimukkala", "anupya@hotmail.ca" , "Ms. Sara-Jane Figliano-Craig", "sara-jane.figliano@tdsb.on.ca", "", "Library", "Twice a month. Email the President/Staff Sponsor to know exact dates.", "Help run library duties smoothly, promote and come up with new event ideas to encourage reading among Haigers.", "Contact: Anupya or ANY of the teacher-librarians. However we do end sign ups at the end of September :( Just keep this in mind next year!","literature-50"),
        EarlHaigClub("Madrigals", "Mylène Li & Hilary Allister", "mmgrls@sympatico.ca & hilary.allister@sympatico.ca" , "Dr. Timothy Sullivan", "timothy.sullivan@tdsb.on.ca", "", "Room 172", "Thursday 8am", "We are an all-girls, student-run, diverse choir! In the past we have performed at Choral Night, Music Showcase, Coffee House, various retirement homes, an elementary school, SOPSS assemblies, and Holt Renfrew.", "Auditions will be held near the end of September, but anyone can try out throughout the year. Just email either Hilary or Mylène and we'll arrange a time for you to audition.","choir-50"),
        EarlHaigClub("Make A Wish Foundation", "Raquel Tso", "raquel8042@hotmail.com" , "Mr. Matsumoto", "", "", "Room 250", "Bi-weekly on Wednesday", "Make A Wish Foundation is a club that will help grant wishes of children with life threatning medical conditions by the power of fundrasing. Our mission is to fundraise enough to adopt a child ($10,000) and grant lots of wishes.   Every month Make A Wish Foundation will have one major fundrasing project and more two to four mini fundrasing ideas.", "New members can grab an application on the SAC board once granted by SAC members. Once the applications are removed, new members can email me at raquel8042@hotmail.com or message me on Facebook.","hospital-3-50"),
        EarlHaigClub("+McKee Math Tutors", "Dawis Chen", "dawischen@yahoo.com" , "Ms.Wun", "lianne.wun@tdsb.on.ca", "", "McKee Public School", "Tuesday morning and Thursday morning starting mid October", "The McKee Math Tutors is a before school math tutoring program targeted towards straightening as well as enriching the mathematical capability of grade three and four students at McKee Public School. The program runs from the late October to the Month of April of the following calendar year where both the general members and the executive team will devote some time before school to give mini-seminars in addition to assist the primary school students in their home work and any other math-related questions they might have.", "Information meeting for general member registration will be hosted before the month of November to give out information about the registration progress. All applications will be done through an online medium. If there are any questions or concerns, feel free to email dawischen@yahoo.com.","literature-50"),
        EarlHaigClub("McKee Reading Buddies", "Wendy Leung", "wendy.leung333@hotmail.com" , "Ms. Zhou", "", "", "McKee McKids", "Every Wednesday (October to May) from 4pm to 5pm", "The McKee Reading Buddies is an after school program targeted towards promoting literacy among youth. The program runs throughout the school year where General Members involved dedicate some time every week to reading and enriching children's skills in literacy at the McKee McKids Centre.", "General Member forms are posted on the McKee Reading board (across the EH library) and are due Thurs, Sept 25. If there are any questions or concerns, please email wendy.leung333@hotmail.com. ","literature-50"),
        EarlHaigClub("Me To We ", "Marissa Kachuck ", "mkachuck@gmail.com" , "Ms. Lue ", "haig.lue@gmail.com", "", "Room 212 ", "Tuesday Morning", "Me To We is a council connected with Free the Children. It's purpose is to spread change through education in the younger generations. The council runs Me To We Week, and other campaigns each month to raise money for our school project in Sierra Leone and other charities that help youth around the world. ", "Members can join by submitting an application and interviewing with the director and assistant director. ",""),
        EarlHaigClub("Micro Film", "Reena Chen", "isrc33@gmail.com" , "Mr.Matsumoto", "", "", "250", "every monday after school", "it is a club where we shoot short film to capture the best moments we r having as a student in earlhaig secondary school. we are also working toward attending film festivals.", "Come to room 250 monday after school.","movie-50"),
        EarlHaigClub("Model United Nations", "Zeid Abughazaleh", "zeid.abughazaleh@gmail.com" , "Frances Lue ", "haig.lue@gmail.com", "", "Room 212", "Wednesday's ", "Model United Nations is a simulation of the real United Nations. We are given a country to represent and we use the opinions and abilities of the country to debate topics that effect the entire world. ", "Members have already been chosen. ",""),
        EarlHaigClub("Music Council", "Hope Chen and Didi Xiong", "Hopechen97@gmail.com, didixiong@ymail.com" , "Mr. Kettle", "", "", "Vocal room - 172", "Monday morning 8-8:30", "The purpose of the club is to create a cohesiveness in the music department by holding events such as the Grade 9 music orientation, Halloween talent show, Christmas movie, etc., and being involved in selling tickets and holding concession stands for music department concerts. The club will also hold occasional fundraisers to fund music events and activities.", "New members can join music council by showing up to the club's Monday morning meetings in the vocal room and providing their contact information to the executives. They can contact hopechen97@gmail.com  if they have any questions about the club or meeting times.","music_transcript-50"),
        EarlHaigClub("Newcomers Club", "Kristen Li", "kristenmuhengli@gmail.com" , "Ms. Storms and Ms. Jundler", "", "", "Room 127", "September 29, October 27, November 24, January 26, February 23, March 30, April 27, May 25", "The newcomers club is a welcoming place for all newcomers to Canada to meet and make new friends. Our goal is to help make transitions into Earl Haig and the Canadian culture more smoothly for newcomers, and to support them along the way. Activities will include monthly club meetings and fund raising events.", "Everyone who is new to Canada can join this club and make new friends! New members can join by coming to our monthly meetings. If you have any questions, please feel free to email the president at kristenmuhengli@gmail.com.",""),
        EarlHaigClub("One Acts", "Ryan Bobkin and Sydney Turrack", "haigoneacts2015@gmail.com" , "Mr. Cameron; Ms. Lue", "haig.lue@gmail.com", "", "102", "N/A", "A student-run theatre festival featuring student-written and directed plays! This year has five plays and will be called, \"Take Five\"!", "Auditions were held in October! We have playwrights, directors, actors, and crew heads already picked. Crew members will be selected in December and January.","comedy-50"),
        EarlHaigClub("Outreach", "Alexandra Churchill", "achurchill97@gmail.com" , "Ms. Donnelly", "", "", "Room 131", "Wednesdays Afterschool", "The club aims to help educate and raise awareness for both a local and global social justice cause.  Outreach will be supporting the North York Harvest Food Bank and Youth Without Shelter in the Youth 4 Youth Campaign.  We will be hosting a food drive, helping in food sortings, and collecting basic essentials for homeless youth.  In our Sustainable Development Campaign, we will be working through Plan Canada and Because I am a Girl to educate students on the importance of sustainable solutions in developing countries.  The four month campaign will highlight the importance of health, education, economic security, and gender equality.  ", "General member sign up will be available on the sac board from September 22-September 26.  As well, those interested can e-mail me or find me in the SAC office for any questions or concerns!",""),
        EarlHaigClub("Peer Tutoring", "Monica Xu", "monicaxu@outlook.com" , "Mr. Im, Ms. Wun", "phillip.im@tdsb.on.ca, lianne.wun@tdsb.on.ca", "", "O'Grady Hall", "Drop in sessions begin in October every Monday-Thursday at 3:40-4:30. Meetings for tutors occur monthly or bi-weekly and tutors will be contacted.", "       Earl Haig Peer Tutoring Committee was founded over a decade ago to service the school community by providing students with a proactive and friendly tutoring service. By pairing students who require support in their learning with knowledgeable and understanding tutors, students are not only able to succeed in school but also find joy in their studies.        While we strive to provide students with tutoring in almost all subject areas, we also aim to teach students various study skills and habits that will enable them to excel in school without the need of a long-term tutor. Peer tutoring is 100% cost-free to you since our tutors are other students from Earl Haig of various grades who have volunteered their time to helping others succeed.        When students join peer tutoring, they are paired up with a responsible and patient tutor and will attend at least one session per week or according to need. Our tutors will work one on one with students or in small groups of less than three students and ensure that their teaching and instruction is tailored to fit the needs of the students.        While our tutors cannot replace the role of a classroom teacher, our tutors can reinforce, strengthen or clarify topics covered in class. Our tutors can aid students with test or exam preparation, as well as answer questions about topics. Most importantly, many of our tutors have or will be receiving certification in tutoring from L2L, an organization that certifies tutors.", "Tutees are welcome to come to any of our drop-in sessions and speak to one of the executives or apply online from our website. Tutors are required to fill out an application from our website.  Please visit http://ehsspeertutoring.weebly.com","classroom-50"),
        EarlHaigClub("Popular Culture Society", "Ashley Chen & Lily Li", "ashley.mchen@outlook.com" , "Jayne Dykstra", "Jayne.Dykstra@tdsb.on.ca", "", "Rm 248", "Thursday afterschool, once or twice a month", "PCS was created to organize various events for fans of popular culture in Asia, namely anime/manga and kpop/kdrama. Our main purpose is to provide a casual discussion forum for students of common interest. Throughout the year we will host drama/anime showings, fan art contests, show recommendation meetings, name that song events, and more. GMs may also sign up for a newsletter to receive upcoming club events and current trending news in the industry.", "Signup on the SAC board at the beginning of the year, or ask to join the Facebook group. Meetings are also public, so feel free to drop by and tell one of the execs that you wish to join!",""),
        EarlHaigClub("Programming Club", "Janet Zhai, Robert Pan", "zhai.janet@gmail.com , robertpan226@gmail.com" , "Mr. Noukhovitch", "sacha.noukhovitch@tdsb.on.ca", "", "room 271", "Friday after school", "To provide extra help to computer science students, as well as to create an environment to practice for the Canadian Computing Competition and ECCO competition (sample questions will be selected for the participants to practice with).  A guest speaker will also be invited to give presentations about Language J (programming language) to club members who are interested.", "Sign ups will be during the first meeting. If students wish to join later in the year, they may attend one of the club's regular meetings and sign up.","cpp-50"),
        EarlHaigClub("Prom committee", "Holly Crystal", "Hollycrystal@rogers.com" , "Ms. Lo Re", "Nicole.lore@tdsb.on.ca", "", "Library", "Thursday mornings ", "Plan the senior prom ", "Applications at the beginning of the school year ",""),
        EarlHaigClub("Reach for the Top", "Mathilde Taylor", "reachforthetopehss@gmail.com" , "Ms. Fradkin", "leslie.fradkin@tdsb.on.ca", "", "Room 344", "Mondays at 3:45", "Reach is a game show type of club, played by two teams of four.  Think Jeopardy, but without the answer being the question.", "Just show up!",""),
        EarlHaigClub("Robotics", "Mahsa Naserifar, Mahtab Naserifar", "m_naseri76@yahoo.com ,  mt_naseri@yahoo.com" , "Dr. Noukhovitch", "sacha.noukhovitch@tdsb.on.ca", "", "Rm. 257", "Thursdays after school", "We are aiming to participate in Junior RoboCup competitions. Joining this club is much easier at the beginning of the school year! For now we are going to work on Junior Light Weight Soccer robot.", "Email the presidents or staff sponsors and request to join!","robot-50"),
        EarlHaigClub("ROOTS", "Bailey Bates", "bballbates@gmail.com" , "Ms. Johnson", "", "", "Room 253", "Tuesday's Afterschool", "Roots is a club that promotes and appreciates black culture.", "Anyone can join just come to a meeting and sign in!","racism-50"),
        EarlHaigClub("SAGE - Students for the Advancement of Global Entrepeneurship", "Eric Dayate, Alexia Wu", "eric.dayate@gmail.com, ehpunchline@gmail.com, sage.haig@gmail.com" , "Mr. Nguyen", "wayne.nguyen@tdsb.on.ca", "", "276", "Thursdays Afterschool", "The purpose of SAGE is to enrich the students of Earl Haig with a solid background in business. As student entrepreneurs, we will be continuing last years business, Punchline, and selling buttons to the school market on multiple occasions as well as businesses outside of school throughout the year.", "Students can join by filling out applications which can be found on the bulletin board across the business office. However, the board needs to be updated and announcements will be planned for when new applications are posted in the last week of September.","bullish-50"),
        EarlHaigClub("Science Club", "Shawn Kang", "kang.shawn@hotmail.com" , "Ms. Fradkin, Ms. Zhou", "leslie.fradkin@tdsb.on.ca", "", "Thursdays after school", "Room 344", "The Earl Haig Science Club organizes science-related activities and events throughout the year for science enthusiasts. Examples include the McMaster Science Olympics and the Guelph Science Olympics. We support the Science department in running contests and competitions. We also bring in guest speakers throughout the year to share their knowledge and experiences with students.", "GM applications will be released towards the end of September. For more information, feel free to visit our website at: http://earlhaigsc.wix.com/home","physics-50"),
        EarlHaigClub("SickKids Foundation ", "Angi Chao ", "angichao97@gmail.com" , "Ms. Wun", " lianne.wun@tdsb.on.ca", "", "Room: 294", "Biweekly on Tuesdays ", "This club inspires and motivates students and the community to invest and donate to SickKids Foundation that financially aids The SickKids Hospital. The hospital takes in millions and millions of young patients every year. These patients have a certain illness that requires medical help. However, SickKids needs financial support to have scientific advances available to improve the lives of children. This club is a fundraising club that will strive to provide support to the Hospital and the foundation by making donations through our events throughout the school year.   ", "General Member applications will be out by Monday September 22 on the SAC board. The meetings will be held in room 294. Questions can be directed to angichao97@gmail.com","hospital-3-50"),
        EarlHaigClub("Social committee ", "Holly Crystal", "Hollycrystal@rogers.com" , "Ms. Lil", "Adrea.lil@tdsb.on.ca", "", "Room 289", "Monday mornings", "To plan semi formal", "Applications at the beginning of each year","social-50"),
        EarlHaigClub("SOPSS Council", "Ryan Bobkin", "ryanbobkin@gmail.com" , "Mr. Kettle", "robert.kettle@tdsb.on.ca", "", "117", "Tuesday mornings", "SOPSS Council is in charge of all Spirit Days and SOPSS assemblies! SOPSS stands for: Student Organization of the Promotion of School Spirit!! It's always a blast with SOPSS!!", "Executive member applications were due September 19th! SOPSS is an awesome council!",""),
        EarlHaigClub("Stage Crew", "Shireen Norouzi", "shireennorouzi@gmail.com" , "Len Hayes", "Len.Hayes@tdsb.on.ca", "", "Cringan Hall", "Thursdays afterschool", "To help Earl Haig students with technical requirements for performances and events. ", "Come to the meetings, and we will add you to the facebook group.","coliseum-50"),
        EarlHaigClub("STEM Society", "John Zhong & Nikki Sigurdson", "wjz.john@gmail.com" , "Mr Noukhovitch", "Sacha.Noukhovitch@tdsb.on.ca", "", "room 271A", "Thursdays Afterschools", "To create a community for students to learn more about cutting edge science, technology, engineering, and medical innovations and careers through discussions and debate with local STEM professionals.", "We will host meetings on Thursdays and anyone who wants to join can attend one of our meetings and fill out a quick application to join.","processor-50"),
        EarlHaigClub("Student Activity Council", "Ethan Godel", "ethangodel@gmail.com" , "Douglas Lawrence ", "douglas.lawrence@tdsb.on.ca", "", "Room 133", "Mondays after school at 4pm", "The Student Activity council (or SAC) is in charge of making sure that student morale is always high. We spearhead of all sorts awesome of events, ranging from social nights, coffee houses, SOPSS performances, spirit days, ECO events, and many more. But most importantly we want to make sure that students' voices are heard! ", "To be on the Student Activity Council one must be elected or appointed to a position. The Student Activity Council Elections are held during the first week of May and the appointed positions will be selected shortly after elections. We encourage all students to take part in the election process, whether it be running for an elected position, applying for an appointed position, or even voting! ","administrator-50"),
        EarlHaigClub("Super Smash Brothers Melee Tournaments Club", "Jason Zhu", "ogdard@gmail.com" , "Ms Bell", " karen.bell@tdsb.com", "", "Classroom", "once-twice a month", "We will be hosting bi-monthly or monthly tournaments at school. If enough members join, money raised from tournaments will be donated to a local charity such as United Way.  ", "New members can apply to join on facebook at the Earl Haig Smashers group, email Jason directly at ogdard@gmail.com or forward their contact info and interest through any existing member. ","joystick-50"),
        EarlHaigClub("Syria Relief Committee ", "Noor al Mamlouk", "noor.mamlouk@gmail.com" , "Joanna Muscatello", "joanna.muscatello@tdsb.on.ca", "", "Third floor - Room not yet confirmed ", "Wednesday Afterschool", "The purpose of this club is to provide relief through a Canadian apolitical organization for refugees affected by the Syrian conflict. Currently there are 9 million Syrian refugees around the world, however most of them are concentrated in Jordan, Lebanon and Turkey. More than half of these refugees are children under the age of 14, and the organization chosen does workshops and camps for children to help them cope in the situation they are in, and they also fund a school in Syria to make sure children are still getting educated despite the state of war.  The club will host events such as a winter clothing drive, in which students can donate winter clothing in good condition and they will be shipped to Turkey during the Christmas holidays. There will also be a Letters of Love campaign, where students get to write empowering, encouraging letters to children. There will also be several movie nights, bake sales, and t-shirt or button sales, where the money donated goes to the organization. ", "There will be forms up on the SAC board for executive and general members. They can contact Noor al Mamlouk via email or facebook (Noor Mamlouk). There will also be a facebook group for all members. ","donate-50"),
        EarlHaigClub("Table Tennis Club", "Kristen Li", "kristenmuhengli@gmail.com" , "Ms.Lai and Ms. Poole", "miss.poole.class@gmail.com", "", "Cafeteria", "Tuesday after school", "Earl Haig table tennis club is set to gather ping pong players and students who are interested in the sports to play together. we will offer skill development workshops and in-club tournaments throughout the school year. In June, interested players can tryout to compete in the tdsb tournament. ", "New members can simply drop in to our after school sessions. ","pingpong-50"),
        EarlHaigClub("TEDx", "Dorothy Lin", "dorothy.z.lin@hotmail.com" , "Mr. Go", "speeritual@gmail.com", "", "Earl Haig Library", "Wednesday Afterschool ", "“TED is a nonprofit devoted to Ideas Worth Spreading. It started out (in 1984) as a conference bringing together people from three worlds: Technology, Entertainment, Design” (ted.com). The EHSS TEDx club hopes to bring the inspiring TED talks to the people of Earl Haig. TEDx at EHSS is affiliated with the Library Learning Commons and strives to bring staff and students together to challenge our conventions of thinking through a live viewing of the annual TEDx Conference.", "New members can join our club by signing up during the Clubs and Council's Fair. They may also contact us through our email: tedxehss@gmail.com",""),
        EarlHaigClub("Triathlon Club", "Jade Levine", "jade-levine@hotmail.com" , "Mr Lawrence", "douglas.lawrence@tdsb.on.ca", "", "N/A", "N/A", "To promote healthy living and sports through triathlon!", "Email me or come and find me at school","time_trial_biking-50"),
        EarlHaigClub("UNICEF", "Simryn Parmar", "myglassishalffull@hotmail.com" , "Madame Rosevelti", "Susana.Rosevelti@tdsb.on.ca", "", "in a languages classroom (usually rooms 250-253)", "Wednesdays", "UNICEF club is dedicated to fundraising for donations which will go to the charity, UNICEF. In the past we have done tons of events from cookie pops to scrabble jewelry. What we will be selling this year is to be determined.", "UNICEF applicants can fill out forms for exec or gm positions starting September 8, 2014 which is the date of our information meeting. We will hand out applications at the meeting but also post them on the SAC board. Completely applications will be dropped off on the SAC board as well and members will be notified of their acceptance through email.","unisef-50"),
        EarlHaigClub("United Way ", "Vivi Diaz-Lada", "vivi.diaz.lada@hotmail.com" , "Mr. D. Lawrence, Ms. A. Lill", "douglas.lawrence@tdsb.on.ca, andrea.lill@tdsb.on.ca", "", "Conference room", "Thursdays after school", "The purpose of this club is to inform and educate students about poverty in the community, and how this charity provides the basic necessities for life in order to allow those in the community to thrive. The United Way council will be hosting the annual United Way CN Tower climb, United Way week from October the 27th to the 31st (which includes Carnival Day), and a variety of volunteering and fundraising events throughout the year! ", "Unfortunately, there are no executive positions left on the council. If students are interested in getting involved with the council in any other way (i.e volunteering, aiding in sponsorships, or participating in events), then they are advised to e-mail Vivi Diaz at vivi.diaz.lada@hotmail.com. New students are always welcome! ",""),
        EarlHaigClub("VISUAL ARTS COUNCIL (VAC)", "Alissa Zilberchteine & Jackie Cheng", "jackiechengxxiii@gmail.com" , "Ms. Sakhavarz", "nazysakhavarz@hotmail.com", "", "Art rooms (301, 302, 303)", "Wednesday mornings", "Involved with Earl Haig visual arts (internally and externally) events throughout the year -Plan, curate, and install art shows in the Wave Gallery -Volunteer at Fashion Event -Paint mural at North York General Hospital -Volunteer at various Claude Watson events (Open House, etc.)", "Members have already been chosen.","brush-50-2"),
        EarlHaigClub("Women in Action", "Amy Ko, Jenny Qin", "amyko971208@hotmail.com, jennyqin@live.ca" , "Ms. Vasavada ", "", "", "rm 309", "Tuesdays after school 3:30pm-4:30pm", "The purpose of this club was actualized after the realization that Earl Haig Secondary School does not have any clubs pertaining to the advancement of women. With the founding of WIA (Women in Action), we will be visiting shelters for homeless women with food as well as donating any profits made by bake sales, or other fundraisers to organizations dedicated to helping women in need such as Action to End Exploitation and North York's Women Shelter. We will also educate young women about their opportunities and encourage them to take chances, whether it be now or in the future during their professional life. We plan on asking businesswomen to come in to talk about how they were able to succeed even against the sexism found in the workplace, as even now women are only being paid 75% of what men are being paid. With this club, we hope that the young women of Earl Haig will be empowered to take chances and to never settle for the stereotypes placed upon them by society, to take action and be wonderful role models for all future women. ", "No applications required for General Members. Applications + Interviews required for Execs.  Contact: Amy Ko (4162209947), Jenny Qin (4169082829) When: Tuesdays after school 3:30pm-4:30pm rm309 ","user_female_3-50"),
        EarlHaigClub("Women's space", "SammiGoldman ZoëWalton", "sammi.g@live.ca zew.sewingmad@gmail.com" , "Ms. Neinhuis", "l.neinhuis@tdsb.on.ca", "", "Art room closest to feild", "thursdays from 3:40 until 4:15", "A safe space for girls to meet new friends, gain social awareness and self awareness through heart talks, spiritual talks and find support in the emotional struggle of becoming a woman. It will involve workshops with strong feminine figures and volunteer opportunities with women's geared charities such as the Red Door", "Show up to one of the short thursday regular meetings in the art room at 3:40 on thursdays or speak with a president about accommodations ","user_female_3-50"),
        EarlHaigClub("World Vision", "Brandon Leung", "brandon-1998@live.ca" , "Mr. Pascua (tentative)", "john.pascua@tdsb.on.ca", "", "TBD", "TBD", "World Vision is one of Earl Haig's largest social justice clubs. We organize a variety of fundraisers and events -  mainly the 30 Hour Famine Overnight event in April. Our purpose is to financially support and advocate for sustainable poverty-relief programs worldwide. In the past two years, we've had celebrities such as Juno Award Winning Artist LIGHTs and the Harlem Globetrotters perform at our events. ", "General Member and Executive (five positions) applications will be out on the World Vision board from mid-September and are due October 3rd. In the new year, leadership opportunities during the 30 Hour Famine Overnight event will be available for all students. If you have any questions feel free to email eh30hourfamine@gmail.com or speak to an Executive. ",""),
        EarlHaigClub("Young Engineers Society ", "John Huang", "123johnhuang@live.ca" , "Ms. Karen Bell", "karen.bell@tdsb.on.ca", "", "Online", "anytime", "The purpose of Young Engineers Society (Y.E.S.) is to assist high school students who have an interest in studying engineering post secondary. Y.E.S. understands the huge workload involved in high school and is here for students to help each other achieve their goals. Y.E.S. offers peer tutoring (Physics,Chemistry,Mathematics), information workshops, and opportunities for students to expand their knowledge and experience in engineering.", "Sign-up on SAC board, and be added to Facebook group. Sign-ups start November 17th and ends on November 28th.  Contact John Huang at (416-624-3666) with any questions. ","dam-50"),
        EarlHaigClub("Youth Initiative", "Kenny Chang", "youthclubeh@gmail.com" , "Ms. Boyd", "Fiona.Boyd@tdsb.on.ca", "", "Rm 250/251", "Every other Monday, starting September 29", "Youth Initiative aims to support the growth of our local community of Toronto/North York. At Youth Initiative, we fund raise money and help out at local shelters in order to support the needy in Toronto, unlike other clubs which tend to support international affairs. We aim to create a better community for ourselves and everyone around. We will be hosting fundraisers throughout the school year and possibly helping out at local shelters.", "Application forms for General Members will be posted on the SAC board(or Youth Initiative club board, if any), on Facebook, and on our club Tumblr page! Listen/Watch the announcements via Haig Radio or HaigTV(main hall), or via the club tumblr and facebook pages for when the applications are out!  Tentative date will be around early-mid September!",""),
        EarlHaigClub("Zoom Student Film Festival", "Ryan Cheng", "rcheng30@yahoo.ca" , "Mr. Raemisch", "walter.raemisch@tdsb.on.ca", "", "Room 202", "Thursdays after school", "The purpose of the club is to plan and prepare for the film festival on May 21th. ", "General member forms will be available sometime in the spring. ","film_reel-50")
    ]
    
    //var earlHaigClubList = [[String]]
    

    override func viewDidLoad() {
        super.viewDidLoad()

        // Uncomment the following line to preserve selection between presentations
        // self.clearsSelectionOnViewWillAppear = false

        // Uncomment the following line to display an Edit button in the navigation bar for this view controller.
        // self.navigationItem.rightBarButtonItem = self.editButtonItem()
        //loadAllData()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    // MARK: - Table view data source

    override func numberOfSectionsInTableView(tableView: UITableView) -> Int {
        // #warning Potentially incomplete method implementation.
        // Return the number of sections.
        return 1
    }

    override func tableView(tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        // #warning Incomplete method implementation.
        // Return the number of rows in the section.
        return earlHaigClubs.count
    }

    override func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
        /*
        let cell = tableView.dequeueReusableCellWithIdentifier("Club Council Name", forIndexPath: indexPath) as UITableViewCell
        

        //NSLog(self.earlHaigClubs[indexPath.row].clubCouncilName)
        cell.textLabel!.text = self.earlHaigClubs[indexPath.row].clubCouncilName
        //cell.textLabel.text = self.earlHaigClubs[indexPath.row];
        //NSLog(cell.textLabel!.text!)
        if self.earlHaigClubs[indexPath.row].clubCouncilName != "" {
            cell.imageView!.image = UIImage(named: self.earlHaigClubs[indexPath.row].imageName)
        }
        */
        
        let cell = tableView.dequeueReusableCellWithIdentifier("Image Cell", forIndexPath: indexPath) as ImageCellTableViewCell
        
        cell.clubTitle!.text = self.earlHaigClubs[indexPath.row].clubCouncilName
        if self.earlHaigClubs[indexPath.row].clubCouncilName != "" {
            cell.clubImage!.image = UIImage(named: self.earlHaigClubs[indexPath.row].imageName)
        }
        return cell
    }
    
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject!) {
        if segue.identifier == "Show Details2"{
            if let indexPath = self.tableView.indexPathForSelectedRow() {
                let clubCouncil = earlHaigClubs[indexPath.row]
                (segue.destinationViewController as ClubDetailsViewController).club = clubCouncil
            }
        }

    }

    
/*
//- (void)tableView:(UITableView *)tableView willDisplayCell:(UITableViewCell *)cell forRowAtIndexPath:(NSIndexPath *)indexPath { ... }
    override func tableView(tableView: UITableView, willDisplayCell cell: UITableViewCell, forRowAtIndexPath indexPath:NSIndexPath)  {
    
        if indexPath.row % 2 == 0 {
            cell.backgroundColor = UIColor.grayColor()
            //cell.setBackgroundColor:[UIColor colorWithRed:.8 green:.8 blue:1 alpha:1]];
            //cell.setBackgroundColor:[UIColor colorWithRed:.8 green:.8 blue:1 alpha:1]];
        }
        else {
            //cell.backgroundColor = UIColor.clearColor()
            //[cell setBackgroundColor:[UIColor clearColor]];
        }
    }
*/


    /*
    // Override to support conditional editing of the table view.
    override func tableView(tableView: UITableView, canEditRowAtIndexPath indexPath: NSIndexPath) -> Bool {
        // Return NO if you do not want the specified item to be editable.
        return true
    }
    */

    /*
    // Override to support editing the table view.
    override func tableView(tableView: UITableView, commitEditingStyle editingStyle: UITableViewCellEditingStyle, forRowAtIndexPath indexPath: NSIndexPath) {
        if editingStyle == .Delete {
            // Delete the row from the data source
            tableView.deleteRowsAtIndexPaths([indexPath], withRowAnimation: .Fade)
        } else if editingStyle == .Insert {
            // Create a new instance of the appropriate class, insert it into the array, and add a new row to the table view
        }    
    }
    */

    /*
    // Override to support rearranging the table view.
    override func tableView(tableView: UITableView, moveRowAtIndexPath fromIndexPath: NSIndexPath, toIndexPath: NSIndexPath) {

    }
    */

    /*
    // Override to support conditional rearranging of the table view.
    override func tableView(tableView: UITableView, canMoveRowAtIndexPath indexPath: NSIndexPath) -> Bool {
        // Return NO if you do not want the item to be re-orderable.
        return true
    }
    */

    /*
    // MARK: - Navigation

    // In a storyboard-based application, you will often want to do a little preparation before navigation
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        // Get the new view controller using [segue destinationViewController].
        // Pass the selected object to the new view controller.
    }
    */

}
